In [3]:
#create obj (ndarray) in numpy
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
#use tuple to create numpy object

arr = np.array((1,2,3,4,5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [9]:
#create 1 dimension array

arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [11]:
#create 2 dimension array
arr = np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(arr)


[[1 2 3 4 5]
 [1 2 3 4 5]]


In [12]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [14]:
#Check how many dimension available

import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5]) #1D 1A
c = np.array([[1, 2, 3], [4, 5, 6]]) # 2D 2A
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]]) # 3D 4A

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [16]:
import numpy as np

arr = np.array([1,2,3,4,5],ndmin=5)
print(arr)
print("number of dimension:",arr.ndim)

[[[[[1 2 3 4 5]]]]]
number of dimension: 5


In [33]:
arr[0][0][0][0][0]

np.int64(1)